import{describe,it,expect,beforeAll,afterAll}from'vitest';import{randomUUID,randomBytes}from'node:crypto';import{buildServer}from'../src/server.ts';import{makeAuth}from'../src/auth.ts';import{authDb,closeDatabase}from'../../../packages/db/src/index.ts';
const enabled=Boolean(process.env.TEST_DATABASE_URL);
describe.skipIf(!enabled)('Authentication and project API boundary',()=>{
 let app:Awaited<ReturnType<typeof buildServer>>,workspaceId:string,projectA:string,projectB:string,owner:string,viewer:string,ownerCookie:string,viewerCookie:string;const origin=process.env.APP_ORIGIN!;
 beforeAll(async()=>{app=await buildServer();const auth=makeAuth(),password=randomBytes(24).toString('base64url');const o=await auth.api.signUpEmail({body:{email:randomUUID()+'@example.invalid',name:'Synthetic API owner',password}}),v=await auth.api.signUpEmail({body:{email:randomUUID()+'@example.invalid',name:'Synthetic API viewer',password}});owner=o.user.id;viewer=v.user.id;const w=await authDb.workspace.create({data:{name:'Synthetic API isolation',members:{create:[{userId:owner,role:'owner'},{userId:viewer,role:'viewer'}]}}});workspaceId=w.id;projectA=(await authDb.project.create({data:{workspaceId,name:'Authorized',members:{create:{userId:viewer,role:'viewer'}}}})).id;projectB=(await authDb.project.create({data:{workspaceId,name:'Other'}})).id;
 async function signIn(email:string){const r=await app.inject({method:'POST',url:'/api/auth/sign-in/email',headers:{origin},payload:{email,password}});expect(r.statusCode).toBe(200);const cookies=r.headers['set-cookie'];return(Array.isArray(cookies)?cookies:[cookies]).map(c=>c!.split(';')[0]).join('; ')}ownerCookie=await signIn(o.user.email);viewerCookie=await signIn(v.user.email)});
 afterAll(async()=>{await authDb.workspace.delete({where:{id:workspaceId}});await authDb.user.deleteMany({where:{id:{in:[owner,viewer]}}});await app?.close();await closeDatabase()});
 it('A02: requires authenticated session and rejects public registration',async()=>{expect((await app.inject('/api/me')).statusCode).toBe(401);expect((await app.inject({method:'POST',url:'/api/auth/sign-up/email',headers:{origin},payload:{}})).statusCode).toBe(403)});
 it('A03/A24: viewer reads assigned project only and cannot inspect another project',async()=>{expect((await app.inject({url:`/api/projects/${projectA}/content`,headers:{cookie:viewerCookie}})).statusCode).toBe(200);for(const collection of['content','connectors','jobs','evidence','documents'])expect((await app.inject({url:`/api/projects/${projectB}/${collection}`,headers:{cookie:viewerCookie}})).statusCode).toBe(404)});
 it('A03: viewer cannot mutate, upload, generate images or manage project membership',async()=>{for(const route of[`/api/projects/${projectA}/missions`,`/api/projects/${projectA}/assets/upload`,`/api/projects/${projectA}/images/generate`,`/api/projects/${projectA}/actions/pause`,`/api/projects/${projectA}/actions/add-member`])expect((await app.inject({method:'POST',url:route,headers:{origin,cookie:viewerCookie},payload:{}})).statusCode).toBe(403)});
 it('A24: cross-origin writes are refused before parsing',async()=>{expect((await app.inject({method:'POST',url:`/api/projects/${projectA}/missions`,headers:{origin:'https://attacker.example.invalid',cookie:ownerCookie},payload:{}})).statusCode).toBe(403)});
 it('A02: owner can create project with valid member relation and no production defaults',async()=>{const r=await app.inject({method:'POST',url:'/api/projects',headers:{origin,cookie:ownerCookie},payload:{name:'Created by API',workspaceId,timezone:'Europe/Berlin',language:'en'}});expect(r.statusCode).toBe(201);expect(r.json().mode).toBe('observe');expect(r.json().paused).toBe(false)});
});
