import {
  test,
  expect,
  type Page,
  type APIRequestContext,
} from "@playwright/test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { randomUUID } from "node:crypto";
// Credentials are generated by the isolated integration setup, ignored by Git and never logged.
function account() {
  return JSON.parse(
    readFileSync(resolve(".runtime/e2e-user.json"), "utf8"),
  ) as { email: string; password: string; projectId: string };
}
const localDate = (date: Date) =>
  new Date(date.getTime() - date.getTimezoneOffset() * 60_000)
    .toISOString()
    .slice(0, 16);
async function login(
  page: Page,
  user: Pick<ReturnType<typeof account>, "email" | "password"> = account(),
) {
  await page.goto("/");
  await page.getByLabel(/^Email/).fill(user.email);
  await page.getByLabel(/^Password/).fill(user.password);
  const submit = async () => {
    const response = page.waitForResponse(
      (r) =>
        r.url().endsWith("/api/auth/sign-in/email") &&
        r.request().method() === "POST",
    );
    await page.getByRole("button", { name: "Sign in", exact: true }).click();
    return response;
  };
  let response = await submit();
  if (response.status() === 429) {
    // Respect the real authentication throttle; never disable it for browser acceptance.
    const seconds = Math.min(
      60,
      Math.max(1, Number(response.headers()["retry-after"]) || 11),
    );
    await page.waitForTimeout(seconds * 1000);
    response = await submit();
  }
  expect(response.status(), "Real sign-in response after server throttle").toBe(
    200,
  );
  await expect(
    page.getByRole("heading", { name: "Your marketing, in orbit." }),
  ).toBeVisible();
}
async function checkedPost(
  request: APIRequestContext,
  path: string,
  data: unknown,
) {
  const response = await request.post(path, {
    data,
    headers: { Origin: "http://localhost:4310" },
  });
  expect(
    response.ok(),
    `API request ${path} returned ${response.status()}`,
  ).toBeTruthy();
  return response.json();
}
async function checkedPut(
  request: APIRequestContext,
  path: string,
  data: unknown,
) {
  const response = await request.put(path, {
    data,
    headers: { Origin: "http://localhost:4310" },
  });
  expect(
    response.ok(),
    `API request ${path} returned ${response.status()}`,
  ).toBeTruthy();
  return response.json();
}
async function newProject(page: Page, name: string) {
  const project = await checkedPost(page.request, "/api/projects", {
    name,
    timezone: "Europe/Berlin",
    language: "en",
  });
  await page.reload();
  const selector = page.locator("#project");
  await expect(selector).toBeAttached();
  if (!(await selector.isVisible()))
    await page
      .getByRole("button", { name: "Open navigation", exact: true })
      .click();
  await selector.selectOption(project.id);
  if (
    await page.getByRole("dialog", { name: "Workspace navigation" }).isVisible()
  )
    await page.keyboard.press("Escape");
  await expect(
    page.getByRole("heading", { name: "Your marketing, in orbit." }),
  ).toBeVisible();
  await expect(page.locator(".mode-band")).toBeVisible();
  return project.id as string;
}
test.describe("Authenticated Orbit workspace, real local API", () => {
  test("knowledge → mission → review → approved test publication → revoke, with actual persistent state", async ({
    page,
  }, testInfo) => {
    test.setTimeout(180_000);
    await page.setViewportSize({ width: 1536, height: 1024 });
    await login(page);
    const projectId = await newProject(page, "EDS Labs · browser acceptance");
    await page.screenshot({
      path: testInfo.outputPath("overview-desktop.png"),
      fullPage: true,
    });
    await page.goto("/knowledge");
    await expect(
      page.getByRole("heading", { name: "Knowledge", exact: true }),
    ).toBeVisible();
    await page.getByRole("tab", { name: "Sources", exact: true }).click();
    await page.screenshot({
      path: testInfo.outputPath("knowledge-desktop.png"),
      fullPage: true,
    });
    await page
      .getByRole("button", { name: "Add source", exact: true })
      .first()
      .click();
    let dialog = page.getByRole("dialog");
    await dialog
      .getByLabel("Name", { exact: false })
      .fill("Browser acceptance source");
    await dialog.getByLabel("Source authority").selectOption("official");
    await dialog.getByLabel("Approved for public use").check();
    await dialog.getByLabel("Approved for model processing").check();
    await dialog
      .getByRole("button", { name: "Add source", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    await page
      .locator(".source-row")
      .filter({ hasText: "Browser acceptance source" })
      .click();
    await page.getByRole("button", { name: "Import", exact: true }).click();
    dialog = page.getByRole("dialog");
    await dialog
      .getByLabel("Stable document identifier")
      .fill("browser-acceptance");
    await dialog
      .getByLabel("Title", { exact: false })
      .fill("Synthetic public product documentation");
    await dialog
      .getByLabel("Document text")
      .fill(
        "Synthetic browser acceptance documentation. Browser status is available. This is isolated test knowledge and not a public product claim.",
      );
    await dialog.getByRole("button", { name: "Import", exact: true }).click();
    await expect(dialog).toHaveCount(0);
    const documents = await (
      await page.request.get(`/api/projects/${projectId}/documents`)
    ).json();
    const documentId = documents.items[0].id as string;
    const unconfirmedEmbedding = await page.request.post(
      `/api/projects/${projectId}/actions/embed-document`,
      {
        data: { documentId },
        headers: { Origin: "http://localhost:4310" },
      },
    );
    expect(unconfirmedEmbedding.status()).toBe(400);
    await page.getByRole("tab", { name: "Library", exact: true }).click();
    await page
      .getByRole("button", {
        name: "Synthetic public product documentation",
        exact: true,
      })
      .click();
    await dialog
      .getByRole("button", { name: "Embed with OpenAI", exact: true })
      .click();
    await expect(dialog).toContainText("paid embeddings");
    await expect(
      dialog.getByLabel(
        "I authorize sending this document's extracted passages to OpenAI for paid embeddings.",
      ),
    ).toBeVisible();
    await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await page.getByRole("tab", { name: "Facts", exact: true }).click();
    await page
      .getByRole("button", { name: "Add fact", exact: true })
      .first()
      .click();
    dialog = page.getByRole("dialog");
    await dialog.getByLabel("Fact key").fill("orbit.browser.status");
    await dialog
      .getByLabel("Value", { exact: false })
      .first()
      .fill("available");
    await dialog
      .getByLabel("Supporting source")
      .selectOption({ label: "Browser acceptance source" });
    await dialog
      .getByLabel("Valid from")
      .fill(localDate(new Date(Date.now() - 3600_000)));
    await dialog
      .getByLabel("Valid until")
      .fill(localDate(new Date(Date.now() + 7 * 86400_000)));
    await dialog.getByLabel("Review status").selectOption("verified");
    await dialog.getByLabel("Approved for public use").check();
    await dialog.getByRole("button", { name: "Save", exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(
      page.getByRole("button", { name: "orbit.browser.status", exact: true }),
    ).toBeVisible();
    const sourceResponse = await page.request.get(
      `/api/projects/${projectId}/sources`,
    );
    const sourcePayload = await sourceResponse.json();
    const sourceId = sourcePayload.items.find(
      (item: { data: { name: string } }) =>
        item.data.name === "Browser acceptance source",
    ).id as string;
    const websiteFact = await checkedPost(
      page.request,
      `/api/projects/${projectId}/facts`,
      {
        key: "orbit.browser.website",
        value: "https://orbit.example.test",
        valueType: "url",
        language: "en",
        sourceId,
        validFrom: new Date(Date.now() - 3600_000).toISOString(),
        validUntil: new Date(Date.now() + 7 * 86400_000).toISOString(),
        status: "verified",
        publicUse: true,
        modelUse: true,
      },
    );
    const requiredLinkFacts = [
      ["Web app", "orbit.browser.app", "https://app.orbit.example.test"],
      [
        "Beta registration",
        "orbit.browser.beta",
        "https://orbit.example.test/beta",
      ],
      [
        "Getting Started",
        "orbit.browser.docs",
        "https://orbit.example.test/docs",
      ],
    ];
    const linkFactIds = new Map<string, string>([
      ["Website", websiteFact.id as string],
    ]);
    for (const [label, key, value] of requiredLinkFacts) {
      const fact = await checkedPost(
        page.request,
        `/api/projects/${projectId}/facts`,
        {
          key,
          value,
          valueType: "url",
          language: "en",
          sourceId,
          validFrom: new Date(Date.now() - 3600_000).toISOString(),
          validUntil: new Date(Date.now() + 7 * 86400_000).toISOString(),
          status: "verified",
          publicUse: true,
          modelUse: true,
        },
      );
      linkFactIds.set(label, fact.id as string);
    }
    await page.goto("/settings");
    await page.getByRole("button", { name: "Review usage rights" }).click();
    dialog = page.getByRole("dialog", { name: "Approve brand usage" });
    await dialog
      .getByLabel(
        "I hold the necessary rights and approve EDS Labs brand usage for this project.",
      )
      .check();
    await dialog.getByRole("button", { name: "Approve project usage" }).click();
    await expect(dialog).toHaveCount(0);
    await expect(
      page.getByText("Rights approved", { exact: true }),
    ).toBeVisible();
    const logoAssets = await (
      await page.request.get(`/api/projects/${projectId}/assets`)
    ).json();
    const logoAssetId = logoAssets.items.find(
      (asset: { data: { type: string } }) =>
        asset.data.type === "original_logo",
    ).id as string;

    await page.getByRole("navigation", { name: "Workspace" })
      .getByRole("link", { name: "Assets" }).click();
    await page.getByRole("button", { name: "Upload asset" }).click();
    dialog = page.getByRole("dialog", { name: "Upload brand asset" });
    await dialog.getByLabel("Asset name").fill("Browser visual asset");
    await dialog.getByLabel("Asset type").selectOption("background");
    await dialog
      .getByLabel("Image file")
      .setInputFiles(resolve("docs/evidence/container-creative-square.png"));
    await dialog.getByLabel("Source / creator").fill("Synthetic local fixture");
    await dialog.getByLabel("License / rights basis").fill("Test fixture only");
    await dialog
      .getByLabel(
        "I confirm that the recorded source and rights information is accurate.",
      )
      .check();
    await dialog.getByRole("button", { name: "Upload as reference" }).click();
    await expect(dialog).toHaveCount(0);
    const assetCard = page.locator(".asset-card").filter({
      hasText: "Browser visual asset",
    });
    await expect(assetCard).toContainText("reference");
    await assetCard
      .getByRole("button", { name: "Approve rights & use" })
      .click();
    await expect(assetCard).toContainText("approved");
    const visualAssets = await (
      await page.request.get(`/api/projects/${projectId}/assets`)
    ).json();
    const visualAssetId = visualAssets.items.find(
      (asset: { data: { name?: string } }) =>
        asset.data.name === "Browser visual asset",
    ).id as string;

    await page.getByRole("navigation", { name: "Workspace" })
      .getByRole("link", { name: "Settings" }).click();
    await page.getByRole("button", { name: "Configure project" }).click();
    dialog = page.getByRole("dialog", { name: "Project configuration" });
    await dialog
      .getByRole("textbox", { name: "Product", exact: true })
      .fill("Orbit browser acceptance");
    await dialog.getByLabel("Audience").fill("Synthetic acceptance audience");
    await dialog
      .getByLabel("Positioning")
      .fill("Synthetic local test workspace");
    await dialog
      .getByLabel("Product marketing strategy")
      .fill("Explain verified product facts");
    await dialog
      .getByLabel("Presale marketing strategy")
      .fill("Use verified presale facts only");
    await dialog.getByLabel("Brand voice (one rule per line)").fill("Clear");
    await dialog
      .getByLabel("Visual brand rules (one per line)")
      .fill("Use clear negative space");
    await dialog
      .getByLabel("Content guardrails (one rule per line)")
      .fill("No return claims");
    await dialog
      .getByLabel("Approved primary CTAs (one per line)")
      .fill("Learn more.");
    await dialog
      .getByLabel("Channel priority (one per line)")
      .fill("test-social");
    await dialog.getByLabel("Internal work language").selectOption("en");
    await dialog.getByLabel("Notification preference").selectOption("none");
    await dialog.getByLabel("Default approved logo").selectOption(logoAssetId);
    for (const label of [
      "Website",
      "Web app",
      "Beta registration",
      "Getting Started",
    ]) {
      const factId = linkFactIds.get(label);
      if (!factId) throw new Error(`Missing browser fact for ${label}`);
      await dialog
        .getByRole("combobox", { name: label, exact: true })
        .selectOption(factId);
    }
    await dialog
      .getByRole("button", { name: "Save configuration version" })
      .click();
    await expect(dialog).toHaveCount(0);
    await expect(page.getByText("Profile v1", { exact: true })).toBeVisible();
    await expect(
      page.getByText("Orbit browser acceptance", { exact: false }),
    ).toBeVisible();

    const verifiedAt = new Date().toISOString();
    await checkedPost(
      page.request,
      `/api/projects/${projectId}/actions/openai-configure`,
      {
        apiKey: "local-browser-image-key".padEnd(24, "x"),
        verifiedModels: ["gpt-5.6-terra", "gpt-image-2.5-flare"],
        rateCard: {
          "gpt-5.6-terra": {
            inputMicrosPerMillion: 2_000_000,
            outputMicrosPerMillion: 12_000_000,
            verifiedAt,
          },
        },
        modelRoutes: {
          fast: "gpt-5.6-terra",
          standard: "gpt-5.6-terra",
          quality: "gpt-5.6-terra",
          escalation: "gpt-5.6-terra",
        },
        imageGeneration: {
          model: "gpt-image-2.5-flare",
          maxCostMicrosPerImage: 250_000,
          pricingVerifiedAt: verifiedAt,
        },
      },
    );
    await page.reload();
    await page.getByRole("navigation", { name: "Workspace" })
      .getByRole("link", { name: "Assets" }).click();
    await page.getByRole("button", { name: "Generate with OpenAI" }).click();
    dialog = page.getByRole("dialog", { name: "Generate reference artwork" });
    await expect(
      dialog.getByLabel(
        "I authorize sending this prompt and the project brand palette to OpenAI and reserve up to $0.25 for this single image.",
      ),
    ).toBeVisible();
    await dialog.getByRole("button", { name: "Cancel" }).click();
    await expect(dialog).toHaveCount(0);
    await page.goto("/knowledge");
    await page.getByRole("tab", { name: "Inspector", exact: true }).click();
    await page.getByLabel("Test question").fill("orbit.browser.status");
    await page.getByRole("button", { name: "Retrieve evidence" }).click();
    await expect(page.locator(".evidence-items")).toContainText(
      "orbit.browser.status",
    );
    await expect(page.locator(".evidence-result")).toContainText(
      "lexical_degraded",
    );
    // Zero budgets: this mandate authorizes only the isolated deterministic executor, never paid APIs.
    await checkedPost(page.request, `/api/projects/${projectId}/policies`, {
      mode: "assisted",
      channels: ["test-social"],
      contentTypes: ["social"],
      allowedOrigins: [],
      startAt: new Date(Date.now() - 3600_000).toISOString(),
      endAt: new Date(Date.now() + 86400_000).toISOString(),
      maxPerDay: 2,
      minIntervalMinutes: 1,
      dailyBudgetMicros: 0,
      monthlyBudgetMicros: 0,
      perRunBudgetMicros: 0,
      approvedPaidTests: false,
    });
    await page.goto("/missions");
    await page
      .getByRole("button", { name: "New mission", exact: true })
      .click();
    dialog = page.getByRole("dialog");
    await dialog
      .getByLabel("Title", { exact: false })
      .fill("Browser acceptance mission");
    await dialog
      .getByLabel("Describe your objective")
      .fill("Explain orbit.browser.status from approved facts.");
    await dialog.getByLabel("Audience").fill("Synthetic acceptance audience");
    await dialog.getByLabel("Measurable target action").fill("Learn more.");
    await dialog.getByLabel("Allowed channels").fill("test-social");
    await dialog.getByLabel("Maximum content packages").fill("1");
    await dialog
      .getByLabel("Start (browser local time)")
      .fill(localDate(new Date(Date.now() - 60000)));
    await dialog
      .getByLabel("End (browser local time)")
      .fill(localDate(new Date(Date.now() + 86400_000)));
    await dialog
      .getByLabel("Required source")
      .selectOption({ label: "Browser acceptance source" });
    await dialog
      .getByRole("button", { name: "Create mission", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    await page
      .getByRole("button", { name: "Browser acceptance mission", exact: true })
      .click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("button", { name: "Run mission" }).click();
    await expect(dialog).toContainText("Mission job queued");
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    let contentId = "";
    await expect
      .poll(
        async () => {
          const response = await page.request.get(
            `/api/projects/${projectId}/content`,
          );
          const payload = await response.json();
          const content = payload.items.find(
            (e: { data: { title: string } }) =>
              e.data.title === "Browser acceptance mission",
          );
          contentId = content?.id || "";
          return Boolean(content);
        },
        { timeout: 60_000 },
      )
      .toBeTruthy();
    await page.goto("/content");
    await page
      .getByRole("button", { name: "Browser acceptance mission", exact: true })
      .click();
    dialog = page.getByRole("dialog");
    await expect(dialog).toContainText("Synthetic test content");
    await dialog.getByRole("button", { name: "Creative", exact: true }).click();
    dialog = page.getByRole("dialog", { name: "Creative production" });
    await dialog.getByLabel("Approved logo asset").selectOption(logoAssetId);
    await dialog
      .getByLabel("Approved visual asset (optional)")
      .selectOption(visualAssetId);
    await dialog.getByRole("button", { name: "Render preview" }).click();
    await expect(
      dialog.getByAltText("Rendered creative preview"),
    ).toBeVisible();
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    dialog = page.getByRole("dialog");
    await dialog.getByRole("button", { name: "Review", exact: true }).click();
    await expect(dialog.locator(".detail-summary")).toContainText("reviewed");
    await dialog.getByRole("button", { name: "Create social variant" }).click();
    await dialog
      .getByLabel("Variant title")
      .fill("Browser acceptance adaptation");
    await dialog.getByLabel("Target channel").fill("test-adaptation");
    await dialog.getByRole("button", { name: "Save variant draft" }).click();
    await expect(dialog).toContainText(
      "Variant saved as draft with parent version",
    );
    const adaptations = await (
      await page.request.get(`/api/projects/${projectId}/content`)
    ).json();
    const variant = adaptations.items.find(
      (e: { data: { title: string } }) =>
        e.data.title === "Browser acceptance adaptation",
    );
    expect(variant.data.parentContentId).toBe(contentId);
    expect(variant.data.status).toBe("draft");
    expect(variant.data.scheduledAt).toBeUndefined();
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await page
      .getByRole("button", { name: "Browser acceptance mission", exact: true })
      .click();
    await dialog
      .getByRole("button", { name: "Approve version", exact: true })
      .click();
    await expect(dialog).toContainText("Action recorded");
    await dialog
      .getByRole("button", { name: "Create test publication", exact: true })
      .click();
    await expect
      .poll(
        async () => {
          const response = await page.request.get(
            `/api/projects/${projectId}/publications`,
          );
          const payload = await response.json();
          return payload.items.find(
            (e: { data: { contentId: string } }) =>
              e.data.contentId === contentId,
          )?.data.status;
        },
        { timeout: 60_000 },
      )
      .toBe("published_test");
    await dialog.getByRole("button", { name: "Close dialog" }).click();
    await page.goto("/knowledge");
    await page.getByRole("tab", { name: "Sources", exact: true }).click();
    await page
      .locator(".source-row")
      .filter({ hasText: "Browser acceptance source" })
      .click();
    await page.getByRole("button", { name: "Revoke access" }).click();
    dialog = page.getByRole("dialog");
    await dialog
      .getByLabel("I confirm revoking access to this source.")
      .check();
    await dialog
      .getByRole("button", { name: "Revoke source", exact: true })
      .click();
    await expect(dialog).toHaveCount(0);
    await expect(page.locator(".source-row")).toContainText("revoked");
    const after = await page.request.get(`/api/projects/${projectId}/content`);
    const payload = await after.json();
    expect(
      payload.items.find((e: { id: string }) => e.id === contentId).data.status,
    ).toBe("needs_review");
  });
  test("390px responsive, keyboard forms, locale and safe errors", async ({
    page,
  }, testInfo) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await login(page);
    await newProject(page, "EDS Labs · mobile acceptance");
    await page.screenshot({
      path: testInfo.outputPath("overview-mobile.png"),
      fullPage: false,
    });
    await page.screenshot({
      path: testInfo.outputPath("overview-mobile-full.png"),
      fullPage: true,
    });
    expect(
      await page.evaluate(
        () => document.documentElement.scrollWidth <= innerWidth,
      ),
    ).toBeTruthy();
    await page
      .getByRole("button", { name: "Open navigation", exact: true })
      .click();
    await expect(
      page.getByRole("dialog", { name: "Workspace navigation" }),
    ).toBeVisible();
    await page.keyboard.press("Escape");
    await expect(
      page.getByRole("dialog", { name: "Workspace navigation" }),
    ).toHaveCount(0);
    await page
      .getByRole("button", { name: "New mission", exact: true })
      .click();
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("Title", { exact: false }).focus();
    await page.keyboard.type("Keyboard accessible mission");
    await page.keyboard.press("Tab");
    await expect(dialog.getByLabel("Describe your objective")).toBeFocused();
    await page.keyboard.press("Escape");
    await expect(dialog).toHaveCount(0);
    await page.goto("/operations");
    await expect(
      page.getByRole("heading", { name: "Worker and dispatch" }),
    ).toBeVisible();
    await expect(
      page.getByText("Pending outbox", { exact: true }),
    ).toBeVisible();
    expect(
      await page.evaluate(
        () => document.documentElement.scrollWidth <= innerWidth,
      ),
    ).toBeTruthy();
    await page.goto("/");
    await page.getByRole("button", { name: "DE", exact: true }).click();
    await expect(
      page.getByRole("heading", { name: "Dein Marketing, im Orbit." }),
    ).toBeVisible();
    await expect(page.locator("html")).toHaveAttribute("lang", "de");
    await page.getByRole("button", { name: "EN", exact: true }).click();
    await page.emulateMedia({ reducedMotion: "reduce" });
    await page.goto("/knowledge");
    await expect(
      page.getByRole("heading", { name: "Knowledge", exact: true }),
    ).toBeVisible();
    await page.getByRole("tab", { name: "Sources", exact: true }).focus();
    await page.keyboard.press("End");
    await expect(
      page.getByRole("tab", { name: "Impact", exact: true }),
    ).toBeFocused();
    expect(
      await page.evaluate(
        () => document.documentElement.scrollWidth <= innerWidth,
      ),
    ).toBeTruthy();
    await page.getByRole("tab", { name: "Sources", exact: true }).click();
    await expect(
      page.getByRole("heading", { name: "Build your source of truth" }),
    ).toBeVisible();
    await page.screenshot({
      path: testInfo.outputPath("knowledge-mobile.png"),
      fullPage: true,
    });
  });
  test("viewer sees read-only controls and server rejects writes", async ({
    page,
  }) => {
    await login(page);
    const projectId = await newProject(
      page,
      "EDS Labs · permission acceptance",
    );
    const viewer = {
      name: "Synthetic viewer",
      email: `orbit-viewer-${randomUUID()}@example.invalid`,
      password: randomUUID() + randomUUID(),
      role: "viewer",
    };
    await page.goto("/settings");
    await page.getByRole("button", { name: "Add member", exact: true }).click();
    const dialog = page.getByRole("dialog");
    await dialog.getByLabel("Name", { exact: false }).fill(viewer.name);
    await dialog.getByLabel("Email", { exact: false }).fill(viewer.email);
    await dialog.getByLabel("Initial password").fill(viewer.password);
    await dialog.getByRole("button", { name: "Save", exact: true }).click();
    await expect(dialog).toHaveCount(0);
    await expect(page.locator(".member-list")).toContainText(viewer.name);
    await page.getByRole("button", { name: "Sign out", exact: true }).click();
    await expect(
      page.getByRole("button", { name: "Sign in", exact: true }),
    ).toBeVisible();
    await login(page, viewer);
    await expect(
      page.getByText("You have read-only access to this project."),
    ).toBeVisible();
    await expect(
      page.getByRole("button", { name: "New mission", exact: true }),
    ).toHaveCount(0);
    await page.goto("/knowledge");
    await expect(
      page.getByRole("button", { name: "Add source", exact: true }),
    ).toHaveCount(0);
    const denied = await page.request.post(
      `/api/projects/${projectId}/sources`,
      {
        data: { name: "forbidden" },
        headers: { Origin: "http://localhost:4310" },
      },
    );
    expect(denied.status()).toBe(403);
    await page.goto("/settings");
    await expect(
      page.getByRole("button", { name: "Add member", exact: true }),
    ).toHaveCount(0);
    await expect(
      page.getByRole("button", { name: "New policy version", exact: true }),
    ).toHaveCount(0);
  });
});

test("editable local brief, private community groups, calendar blocks and owner operator boundaries", async ({
  page,
}, testInfo) => {
  test.setTimeout(120_000);
  await login(page);
  const projectId = await newProject(page, "EDS Labs · editorial acceptance");
  const source = await checkedPost(
    page.request,
    `/api/projects/${projectId}/sources`,
    {
      name: "Editorial acceptance source",
      type: "manual",
      publicUse: true,
      modelUse: false,
      authority: "official",
      maxAgeHours: 168,
    },
  );
  const websiteFact = await checkedPost(
    page.request,
    `/api/projects/${projectId}/facts`,
    {
      key: "orbit.editorial.website",
      value: "https://orbit.example.test/editorial",
      valueType: "url",
      language: "en",
      sourceId: source.id,
      validFrom: new Date(Date.now() - 3600_000).toISOString(),
      validUntil: new Date(Date.now() + 7 * 86400_000).toISOString(),
      status: "verified",
      publicUse: true,
      modelUse: false,
    },
  );
  await checkedPut(
    page.request,
    `/api/projects/${projectId}/marketing-profile`,
    {
      productName: "Orbit editorial acceptance",
      contentLanguage: "en",
      internalLanguage: "en",
      audience: "Synthetic documentation readers",
      positioning: "Synthetic local test workspace",
      productStrategy: "Explain verified product facts",
      presaleStrategy: "Use verified presale facts only",
      voice: ["Clear"],
      guardrails: ["No return claims"],
      primaryCtas: ["Learn more."],
      channelPriority: ["test-editorial"],
      notificationPreference: "none",
      officialLinks: [
        {
          label: "Website",
          url: "https://orbit.example.test/editorial",
          factId: websiteFact.id,
        },
      ],
      assetPolicy: "approved_only",
    },
  );
  await page.goto("/missions");
  await page.getByRole("button", { name: "Start from a brief" }).click();
  let dialog = page.getByRole("dialog");
  const brief =
    "Explain document exports. Help readers find the approved documentation.";
  await dialog.getByLabel("Your brief").fill(brief);
  await dialog
    .getByRole("button", { name: "Prepare editable proposal" })
    .click();
  await expect(dialog).toContainText("Complete before creation");
  await dialog
    .getByRole("button", { name: "Complete structured mission" })
    .click();
  await expect(dialog.getByLabel("Describe your objective")).toHaveValue(brief);
  await expect(dialog.getByLabel("Maximum content packages")).toHaveValue("");
  await expect(dialog.getByLabel("Allow live publication")).not.toBeChecked();
  await dialog
    .getByLabel("Title", { exact: false })
    .fill("Editorial question mission");
  await dialog.getByLabel("Product / offering").fill("Synthetic documentation");
  await dialog
    .getByLabel("Allowed topics")
    .fill("document export, documentation");
  await dialog.getByLabel("Audience").fill("Synthetic documentation readers");
  await dialog.getByLabel("Measurable target action").fill("Learn more.");
  await dialog.getByLabel("Allowed channels").fill("test-editorial");
  await dialog.getByLabel("Maximum content packages").fill("1");
  await dialog
    .getByLabel("Start (browser local time)")
    .fill(localDate(new Date(Date.now() - 60000)));
  await dialog
    .getByLabel("End (browser local time)")
    .fill(localDate(new Date(Date.now() + 86400_000)));
  await dialog.getByLabel("Required source").selectOption(source.id);
  await dialog
    .getByRole("button", { name: "Create mission", exact: true })
    .click();
  await expect(dialog).toHaveCount(0);
  const missions = await (
    await page.request.get(`/api/projects/${projectId}/missions`)
  ).json();
  expect(missions.items[0].data.allowedActions).not.toContain("publish_live");
  expect(missions.items[0].data.allowedTopics).toEqual([
    "document export",
    "documentation",
  ]);
  await page.goto("/content");
  await page.getByRole("button", { name: "Community questions" }).click();
  await page
    .getByRole("button", { name: "Import authorized questions" })
    .click();
  dialog = page.getByRole("dialog");
  await dialog
    .getByLabel("Stable import label")
    .fill("Synthetic authorized question export");
  await dialog
    .getByLabel("Questions, one per line")
    .fill(
      "How can I export documents?\nCan I export documents please?\nI have a complaint about a refund",
    );
  await dialog.getByLabel("I am authorized to import").check();
  await dialog.getByRole("button", { name: "Import and group" }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole("table").getByRole("row")).toHaveCount(3);
  await page
    .getByRole("button", { name: "How can I export documents?", exact: true })
    .click();
  dialog = page.getByRole("dialog");
  await expect(dialog).toContainText("No public reply permission");
  await dialog
    .getByLabel("Internal mission")
    .selectOption(missions.items[0].id);
  await dialog
    .getByRole("button", { name: "Link mission", exact: true })
    .click();
  await expect(dialog).toContainText("Linked missions: 1");
  await dialog.getByRole("button", { name: "Close dialog" }).click();
  await page.screenshot({
    path: testInfo.outputPath("community-desktop.png"),
    fullPage: true,
  });
  await page.goto("/calendar");
  await page.getByRole("button", { name: "Add calendar block" }).click();
  dialog = page.getByRole("dialog");
  await dialog.getByLabel("Block title").fill("Synthetic editorial blackout");
  await dialog
    .getByLabel("Block starts")
    .fill(localDate(new Date(Date.now() + 3600_000)));
  await dialog
    .getByLabel("Block ends")
    .fill(localDate(new Date(Date.now() + 7200_000)));
  await dialog
    .getByLabel("Reason")
    .fill("Synthetic operator acceptance interval");
  await dialog.getByRole("button", { name: "Block this interval" }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.locator(".calendar-block-row")).toContainText(
    "Synthetic editorial blackout",
  );
  await page.getByRole("button", { name: "Release block" }).click();
  await expect(page.locator(".calendar-block-row")).toHaveCount(0);
  const fact = await checkedPost(
    page.request,
    `/api/projects/${projectId}/facts`,
    {
      key: "editorial.export.status",
      value: "available",
      valueType: "status",
      language: "en",
      sourceId: source.id,
      validFrom: new Date(Date.now() - 3600_000).toISOString(),
      status: "verified",
      publicUse: true,
      modelUse: false,
    },
  );
  await page.goto("/knowledge");
  await page.getByRole("tab", { name: "Facts", exact: true }).click();
  await page
    .getByRole("button", { name: "editorial.export.status", exact: true })
    .click();
  dialog = page.getByRole("dialog");
  await dialog
    .getByRole("button", { name: "Withdraw fact", exact: true })
    .click();
  await dialog.getByLabel("Withdraw this fact from future use").check();
  await dialog
    .getByRole("button", { name: "Withdraw version", exact: true })
    .click();
  await expect(dialog).toHaveCount(0);
  const facts = await (
    await page.request.get(`/api/projects/${projectId}/facts`)
  ).json();
  expect(
    facts.items.find((f: { id: string }) => f.id === fact.id).data.status,
  ).toBe("revoked");
  await page.getByRole("tab", { name: "Health", exact: true }).click();
  await expect(
    page.getByRole("heading", { name: "Embedding index generations" }),
  ).toBeVisible();
  await page.getByRole("button", { name: "Prepare index generation" }).click();
  await expect(
    page
      .getByRole("dialog")
      .getByRole("button", { name: "Prepare without model call" }),
  ).toBeVisible();
  await page.keyboard.press("Escape");
  await page.goto("/analytics");
  await page
    .getByRole("button", { name: "Import from Matomo", exact: true })
    .click();
  await expect(page.getByRole("dialog")).toContainText(
    "Configure a Matomo connector first",
  );
  await page.keyboard.press("Escape");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/knowledge");
  await page.getByRole("tab", { name: "Health", exact: true }).click();
  await expect(
    page.getByRole("heading", { name: "Embedding index generations" }),
  ).toBeVisible();
  expect(
    await page.evaluate(
      () => document.documentElement.scrollWidth <= innerWidth,
    ),
  ).toBeTruthy();
  await page.screenshot({
    path: testInfo.outputPath("operator-mobile.png"),
    fullPage: true,
  });
});

test("index activation is offered only after evaluation", async ({ page }) => {
  await login(page);
  const projectId = await newProject(
    page,
    "EDS Labs · index activation acceptance",
  );
  const profile = "openai:text-embedding-3-small:1536:chunk-v1";
  await page.route(`**/api/projects/${projectId}/indexes?*`, (route) =>
    route.fulfill({
      json: {
        items: [
          {
            id: "71e75f94-2c6c-443e-811d-e8a2b9833432",
            generation: 2,
            profile,
            state: "evaluated",
            manifest: [{ chunkId: "test-chunk" }],
            evaluation: { passed: true, provenance: "live" },
          },
          {
            id: "e68d8669-a667-43f9-a766-ae2d72b5f86e",
            generation: 3,
            profile,
            state: "building",
            manifest: [],
          },
          {
            id: "ec2f0d83-4527-4342-a5a0-18409c233c73",
            generation: 1,
            profile,
            state: "active",
            manifest: [],
          },
        ],
      },
    }),
  );
  await page.goto("/knowledge");
  const evaluated = page
    .locator(".index-generation")
    .filter({ hasText: "Generation 2" });
  const building = page
    .locator(".index-generation")
    .filter({ hasText: "Generation 3" });
  await expect(
    evaluated.getByRole("button", { name: "Activate" }),
  ).toBeVisible();
  await expect(building.getByRole("button", { name: "Activate" })).toHaveCount(
    0,
  );
  await expect(
    building.getByRole("button", { name: "Evaluate" }),
  ).toBeVisible();
  await evaluated.getByRole("button", { name: "Activate" }).click();
  await expect(page.getByRole("dialog")).toContainText(
    "Activate index generation 2",
  );
  await expect(
    page.getByRole("dialog").getByRole("button", {
      name: "Apply generation change",
    }),
  ).toBeVisible();
});

test("OpenAI configuration loads a persisted rate card into the settings form", async ({
  page,
}) => {
  test.setTimeout(120_000);
  await login(page);
  const projectId = await newProject(
    page,
    "EDS Labs · OpenAI settings acceptance",
  );
  const verifiedAt = new Date().toISOString();
  const rateCard = {
    "gpt-5.6-terra": {
      inputMicrosPerMillion: 2_000_000,
      outputMicrosPerMillion: 12_000_000,
      verifiedAt,
    },
  };
  await checkedPost(
    page.request,
    `/api/projects/${projectId}/actions/openai-configure`,
    {
      apiKey: "local-test-openai-key".padEnd(20, "x"),
      verifiedModels: ["gpt-5.6-terra"],
      rateCard,
      modelRoutes: {
        fast: "gpt-5.6-terra",
        standard: "gpt-5.6-terra",
        quality: "gpt-5.6-terra",
        escalation: "gpt-5.6-terra",
      },
    },
  );
  await page.goto("/settings");
  await page.getByRole("button", { name: "Configure OpenAI" }).click();
  const dialog = page.getByRole("dialog", { name: "OpenAI configuration" });
  await expect(
    dialog.getByLabel(
      "Current OpenAI rate card (JSON, USD micros per million tokens)",
    ),
  ).toHaveValue(JSON.stringify(rateCard, null, 2));
});
